### pp4dl notebook 1-1
##### Summary
This is the first self learning hands-on notebook for book *Programming PyTorch for Deep Learning* (pp4dl)

In [2]:
import torch

##### Basic operations

Other than what is shown in chapter 1 of the book *PyTorch recipes: a problem-solution approach*, basic tensor operations can be done more easily by directly using the operands or using methods provided in the `Tensor` class, without the hassle of using `torch.something()` (e.g., `torch.add()`, `torch.mul()`). See the official <a href="https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html#operations-on-tensors">tutorial</a> as an example.

In [3]:
x = torch.rand(6) # this gives you a vector of dimension=6
v = torch.rand(6)
a = 6

In [7]:
# tensor sum
y1 = x + v
y2 = x.add(v)

In [8]:
y1

tensor([1.0198, 0.8215, 1.6252, 1.4219, 0.7120, 1.0644])

In [9]:
y2

tensor([1.0198, 0.8215, 1.6252, 1.4219, 0.7120, 1.0644])

In [10]:
y1==y2

tensor([True, True, True, True, True, True])

In [11]:
torch.equal(y1,y2)

True

In [14]:
# tensor multiply with constant
print(x.mul(a))
print(x * a)

tensor([0.8915, 3.9878, 4.8932, 3.2829, 0.0614, 1.5882])
tensor([0.8915, 3.9878, 4.8932, 3.2829, 0.0614, 1.5882])


In [15]:
# entry-wise tensor multiplication
print(x.mul(v))
print(x * v)

tensor([0.1295, 0.1042, 0.6603, 0.4786, 0.0072, 0.2117])
tensor([0.1295, 0.1042, 0.6603, 0.4786, 0.0072, 0.2117])


In [16]:
# linear algebra muliplication
print(x.matmul(v))
print(x @ v) # note that the symbol @ works as the operands for inner-product of two vectors that are dimensionally compatitable

tensor(1.5915)
tensor(1.5915)


In [17]:
# using method item() to extract the value of a scalar, zero-dimension, tensor
x.matmul(v).item()

1.5914591550827026

In [19]:
(x @ v).item()

1.5914591550827026

In [53]:
# Product between matrix and vector in a linear algebra manner
W = torch.rand(2,6)
print(f'W is a {W.shape[0]}-by-{W.size()[1]} matrix')

W is a 2-by-6 matrix


In [67]:
x.matmul(W.T) # in this way, vector x will be treated as a row vector of 1x6, so we need to transpose matrix W

tensor([1.1986, 1.7664])

In [62]:
x @ W.T # this is equivalent to the above line of code

tensor([1.1986, 1.7664])

In [63]:
W.matmul(x) # in this way, x will be automatically interpreted as a column vector

tensor([1.1986, 1.7664])

In [68]:
W @ x # in this way, x will be automatically interpreted as a column vector

tensor([1.1986, 1.7664])

In [77]:
# Product between matrix and vector in element-wise manner
print(f'Recall that W is a {W.shape[0]}-by-{W.size()[1]} matrix')
print(f'Vector x has a dimension of {x.shape[-1]}, the operaiton W*x gives the following matrix\n')
print(W*x) # each row of W will be multiplied by vector x in an element-wise manner 
print(torch.equal(W*x,x*W))
print(torch.equal(W.mul(x),W*x))

Recall that W is a 2-by-6 matrix
Vector x has a dimension of 6, the operaiton W*x gives the following matrix

tensor([[2.1768e-02, 5.5741e-01, 4.2259e-01, 3.2947e-03, 2.7193e-04, 1.9330e-01],
        [3.4191e-02, 3.0405e-01, 7.2417e-01, 5.0596e-01, 6.1589e-03, 1.9187e-01]])
True
True


In [23]:
# type of a tensor
print(x.matmul(v).type())
print(x.matmul(v).dtype)

torch.FloatTensor
torch.float32


In [31]:
# shape or size of a tensor
print(f'vectors x and y has dimension {x.shape[-1]} and {v.size()[-1]} respectively') # in [-1], -1 is to denote the default dimension which is same as leaving blank [] in matlab

vectors x and y has dimension 6 and 6 respectively
torch.Size([])


In [43]:
# dimensionality of tensors
print(f'{x.matmul(v)} is a zero-dimensional tensor, its size is {x.matmul(v).shape}')
print(f'{x.matmul(v).reshape(1,)} is a one-dimensional tensor, it size is {x.matmul(v).reshape(1,).shape}') # use reshape() to change the shape of the tensor, just like the matlab
print(f'{x.matmul(v).reshape(1,)} is a {x.matmul(v).reshape(1,).shape[-1]}-dimensional tensor')

1.5914591550827026 is a zero-dimensional tensor, its size is torch.Size([])
tensor([1.5915]) is a one-dimensional tensor, it size is torch.Size([1])
tensor([1.5915]) is a 1-dimensional tensor


In [134]:
# increase the dimensionality before doing concatenation
print(f'W is a matrix of {W.shape[0]}x{W.size()[1]}')
print(f'\nNow we want to concatenate x with vector v, by putting x above or below v to form a matrix of 2x{x.size()[-1]}')
print('\nBut we must first convert vectors x, v into a 2-D tensors')
print('\nNote the original vector x:')
print(x)
#print(x.shape)
print('\nNote the converted vector x with increased dimension, an addition pair of [] appears')
x_new = x.reshape(1,len(x))
print(x_new)
v_new = v.reshape(1,len(v))
X = torch.cat((x_new,v_new),0)
print(f'\nLet\'s apply same technique to vector v, then we do the concatenation and see\n{X}')
# torch.cat((x_new,v_new),0)

W is a matrix of 2x6

Now we want to concatenate x with vector v, by putting x above or below v to form a matrix of 2x6

But we must first convert vectors x, v into a 2-D tensors

Note the original vector x:
tensor([0.1486, 0.6646, 0.8155, 0.5471, 0.0102, 0.2647])

Note the converted vector x with increased dimension, an addition pair of [] appears
tensor([[0.1486, 0.6646, 0.8155, 0.5471, 0.0102, 0.2647]])

Let's apply same technique to vector v, then we do the concatenation and see
tensor([[0.1486, 0.6646, 0.8155, 0.5471, 0.0102, 0.2647],
        [0.8712, 0.1568, 0.8096, 0.8748, 0.7018, 0.7997]])


In [152]:
# Permute the dimension order of a tensor

# # increase the dimensionality of matrix W, so that it is a 3-D tensor now
# W_new = W.reshape(1,W.shape[0],-1)
# print(f'W_new now looks like this\n{W_new}')
# X_new = X.reshape_as(W_new) # use method reshape_as() for similicity to make the shape of X_new the same as W_new
# print(f'\nX_new looks like this\n{X_new}')
# M = torch.cat((W_new,X_new),dim=0)
# print(f'\nThe concatenation of W_new and X_new makes a 3-D tensor:\n{M}')

A = torch.ones(1,3,6)
print(f'Our matrix A looks like this:\n{A}')
B = A.mul(2)
print(f'\nOur matrix B looks like this:\n{B}')
C = torch.cat((A,B),dim=0)
print(f'\nConcatenation of A above B looks like this:\n{C}')

Our matrix A looks like this:
tensor([[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]])

Our matrix B looks like this:
tensor([[[2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2.]]])

Concatenation of A above B looks like this:
tensor([[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2.]]])


In [166]:
C.permute(0,1,2) # note the order and name of dimensions, this line actually change nothing of the dimension order

tensor([[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2.]]])

In [164]:
print(C.permute(1,2,0))
print(C.permute(1,2,0).size())
print(f'\nEach "layer" of the tensor is\n{C.permute(1,2,0)[0,:,:]}')

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.],
         [1., 2.],
         [1., 2.],
         [1., 2.]],

        [[1., 2.],
         [1., 2.],
         [1., 2.],
         [1., 2.],
         [1., 2.],
         [1., 2.]],

        [[1., 2.],
         [1., 2.],
         [1., 2.],
         [1., 2.],
         [1., 2.],
         [1., 2.]]])
torch.Size([3, 6, 2])

Each "layer" of the tensor is
tensor([[1., 2.],
        [1., 2.],
        [1., 2.],
        [1., 2.],
        [1., 2.],
        [1., 2.]])


In [165]:
print(C.permute(2,0,1))
print(C.permute(2,0,1).size())
print(f'\nEach "layer" of the tensor is\n{C.permute(2,0,1)[0,:,:]}')

tensor([[[1., 1., 1.],
         [2., 2., 2.]],

        [[1., 1., 1.],
         [2., 2., 2.]],

        [[1., 1., 1.],
         [2., 2., 2.]],

        [[1., 1., 1.],
         [2., 2., 2.]],

        [[1., 1., 1.],
         [2., 2., 2.]],

        [[1., 1., 1.],
         [2., 2., 2.]]])
torch.Size([6, 2, 3])

Each "layer" of the tensor is
tensor([[1., 1., 1.],
        [2., 2., 2.]])


In [167]:
print(C.permute(2,1,0))
print(C.permute(2,1,0).size())
print(f'\nEach "layer" of the tensor is\n{C.permute(2,1,0)[0,:,:]}')

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[1., 2.],
         [1., 2.],
         [1., 2.]]])
torch.Size([6, 3, 2])

Each "layer" of the tensor is
tensor([[1., 2.],
        [1., 2.],
        [1., 2.]])


##### Quick summary of `permute()` and dimension orders in PyTorch

1. 正如上方的代码所示，在PyTorch中，无论Tensor有多少维度，“0” 代表其最高维度，“1” 和 “2” 代表第二、第三维度。
    * 例如，一个3-D Tensor，可以将其想象成$N$个/层矩阵叠起来，则0代表数据按层叠加的方向/维度，1代表每层矩阵中数据排成一列的方向/维度，2代表每层矩阵中数据排成一行的方向/维度
    * 或者例如一个2-D Tensor，其实就是一个矩阵，这时0为最高维度，1是第二维度，没有第三维度；这样，0就代表该矩阵中数据排成一列的方向/维度，1则代表该矩阵中数据排成一行的方向/维度。例如我们有一个矩阵$\mathbf{A}\in\mathbb{R}^{m\times n}$，
        * 使用`A.sum(dim=0)`我们将得到一个 $n$ 维（行）向量 $\mathbf{a}=[a_1,a_2,\dots,a_n]$, 其中$a_i=\sum_{j=1}^{m}A_{i,j}, \forall i=1,2,\dots,n$
        * 同理，`A.sum(dim=1)`将输出一个 $m$ 维（列）向量 $\mathbf{a}=[a_1,a_2,\dots,a_m]^T$, 其中$a_j=\sum_{i=1}^{n}A_{i,j}, \forall j=1,2,\dots,m$
        
2. 使用`permute()`可以灵活的交换Tensor的各个维度，如同将一个“方块”进行旋转。可以将“方块”从正上方所看到的形状，想象成Tensor通过`permute()`交换维度之后，每一层数据的形状，如下图所示
![permute oder](./permute-tensor-dimension-order.png)

In [ ]:
# memory saving operation like add_