##### 2-3 Summary
In this note we do some basic statistics

In [1]:
import torch
import numpy as np

First, let's use or seed 666 and prepare some random numbers from both uniform distribution and normal distribution

In [2]:
myseed = 666
myseed

666

In [21]:
torch.manual_seed(myseed)
# uniform distribution
num_samples_u1 = 200
num_samples_u2 = (4,50)
unf_from = 3
unf_to = 7
xu1 = torch.Tensor(num_samples_u1).uniform_(unf_from,unf_to) # this generates a vector
xu2 = torch.Tensor(size=num_samples_u2).uniform_(unf_from,unf_to) # this generates a matrix

# normal distribution
mu = torch.Tensor((1,)).uniform_(0,10).tolist()[0] # this is a float number
var = torch.Tensor((1,)).uniform_(1,2) # this is a tensor
std = torch.sqrt(var).tolist()[0] # now this is a float number
xn1 = torch.normal(mu,std,size=(4,50))

In [22]:
xu1.shape

torch.Size([200])

In [23]:
xu2.shape

torch.Size([4, 50])

In [24]:
mu

0.9447163343429565

In [25]:
std

1.2067664861679077

In [26]:
xn1.shape

torch.Size([4, 50])

##### Mean, median, mode, and variance
Now let's find the mean and other statistics with the data we generated and PyTorch

In [27]:
mean_xu1 = torch.mean(xu1)
mean_xu1

tensor(4.8489)

In [30]:
mean_xu1 = torch.mean(xu2,dim=0) # this computes the mean of each column
mean_xu1

tensor([3.7503, 5.4934, 4.4330, 4.9035, 4.3934, 5.5074, 5.1164, 6.4177, 5.7957,
        4.1885, 4.5731, 5.4794, 5.1549, 5.3315, 4.9349, 4.9899, 5.2316, 5.2330,
        4.9208, 4.0098, 5.0352, 5.0241, 4.2169, 3.8161, 4.8836, 5.5552, 5.3562,
        4.7586, 4.6672, 4.1459, 4.9479, 5.0256, 5.1494, 4.6811, 5.4451, 3.9756,
        4.9959, 5.1403, 5.1759, 5.0407, 5.2402, 5.0127, 5.2263, 4.0064, 5.1929,
        4.2427, 5.8292, 5.0571, 5.0327, 5.1899])

In [32]:
mean_xu1.shape

torch.Size([50])

In [31]:
mean_xu2 = torch.mean(xu2,dim=1) # this computes the mean of each row
mean_xu2

tensor([5.0744, 4.8938, 4.9097, 4.8760])

In [34]:
mean_xn1 = torch.mean(xn1,dim=0)
mean_xn1

tensor([ 2.0197,  0.0442,  2.0685,  1.1290,  0.2873, -0.0504,  1.0093,  1.5484,
         2.0560,  1.3254, -0.4761,  0.7700,  1.9087,  0.7257,  0.7613,  0.4783,
         0.3638,  0.3205,  0.8334,  1.7096,  0.7225,  0.9616,  0.5277,  1.0337,
         0.4989,  1.2463,  0.3820,  1.1675,  0.4969,  0.3297,  1.8535,  0.1824,
         0.6311,  1.2271,  0.4382,  0.5721,  0.7661,  0.6623,  0.2628,  0.2451,
         0.9482,  0.5749,  1.0426,  1.5270,  0.0412,  1.1882,  1.0647,  1.2649,
         0.6645,  0.5166])

In [35]:
mean_xn1.shape

torch.Size([50])

In [36]:
mean_xn2 = torch.mean(xn1,dim=1)
mean_xn2

tensor([0.6724, 0.7078, 1.0031, 0.9666])

Median and mode can be found in a similar way, just to repalce `torch.mean(input,dim)` with `torch.median(input,dim)` or `torch.mod(input,dim)`