# About
In this notebook, we practice **basic PyTorch operations** by following chapter 1 of the book *Deep learning with PyTorch: quick start guide*

In [1]:
import torch
import numpy as np

#####
Let's first do some convertion between array/tensor in numpy and PyTorch

In [2]:
xnp = np.array([[1,2,3],[4,5,6]])

In [3]:
xnp

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
xnp.dtype # show the data type in the memory

dtype('int32')

In [5]:
type(xnp) # show the class of the object

numpy.ndarray

In [6]:
yt = torch.tensor([[7,8,9],[10,11,12]])
yt

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [7]:
yt.dtype # show the data type in the memory

torch.int64

In [8]:
type(yt) # show the class of the object

torch.Tensor

In [9]:
yt.type() # show the detailed pytorch class

'torch.LongTensor'

In [10]:
# observe the data type/class of the sum
f1 = yt + xnp # this operation cast the result into an pytorch tensor object with dtype=int64
f1

tensor([[ 8, 10, 12],
        [14, 16, 18]])

In [11]:
f1.dtype

torch.int64

In [12]:
f1.type()

'torch.LongTensor'

In [46]:
# Note that the following will through an error since tensor.add() requires that the input muust be tensors
# f2 = yt.add(xnp,dtype=torch.int32)

In [14]:
f1.int()

tensor([[ 8, 10, 12],
        [14, 16, 18]], dtype=torch.int32)

In [15]:
f1.float()

tensor([[ 8., 10., 12.],
        [14., 16., 18.]])

In [16]:
f1.long()

tensor([[ 8, 10, 12],
        [14, 16, 18]])

In [17]:
f1.type()

'torch.LongTensor'

In [18]:
f1.dtype

torch.int64

In [19]:
# create pytorch tensor from numpy array
xt = torch.from_numpy(xnp)
print(xt)
print(xt.type())

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
torch.IntTensor


In [32]:
# create pytorch tensor from numpy array
xt = torch.from_numpy(xnp)
xt.dtype

torch.int32

In [43]:
xt1=xt.long() # convert tensor xt into int64/longtensor from int32
xt1.dtype

torch.int64

##### CAUTION
In pytorch, calling methods of a tensor-class object, won't change the object itself. E.g., in the above lines, if we only hit `xt.long()` followed by `xt.dtype` we will see the dtype of xt is still shown as `torch.int32`. If one wants to change the object, then assignment like `xt=xt.long()` should be used. Similar effects go for `tensor.add()` or `tensor.mul()` etc. Alternative to using assignment operation, one can also use in place operations like `x.add_()` but in general this approach is not safe and not the best practice to recommend.

In [45]:
# First change the dtype in numpy and then conver to torch tensor
# xnp2 = xnp.astype(np.int64)
xt2 = torch.from_numpy(xnp.astype(np.int64))
print(xt2)
print(xt2.type())

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.LongTensor


##### CAUTION
Note that numpy arrays and the **directly** converted pytorch tensor share the same memory space, i.e., change the source numpy array can also change the elements in the converted pytorch tensor

In [47]:
xnp

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
xnp[0][1] = 10
xnp

array([[ 1, 10,  3],
       [ 4,  5,  6]])

In [50]:
xt # since xt is the tensor directly converted from numpy array xnp, so xt[0][1] will change accordingly

tensor([[ 1, 10,  3],
        [ 4,  5,  6]], dtype=torch.int32)

In [51]:
xt1 # since xt1 is constructed by xt.long(), not directly from xnp, so it won't change as xnp changes

tensor([[1, 2, 3],
        [4, 5, 6]])

In [53]:
xt2 # xt2 is converted from xt1, but before conversion, xnp undergoes a dtype change, so not a directly conversion from xnp

tensor([[1, 2, 3],
        [4, 5, 6]])